### ISSUE TITLE
Problem with WP Rocket / Composer / Pimple version

### ISSUE THREAD

**Issue by erralb** [Rarst/wps#14]
Hi,

I'm having an issue installing the WP Rocket plugin trough Composer because of a Pimple version dependency.
I've already open an issue on roots.io : 

https://discourse.roots.io/t/problem-with-wp-rocket-and-composer-in-bedrock/21217

Would it be possible to use wps with a new Pimple version ?

Cheers

**Comment by Rarst** [comment]
Composer _tells_ you wps has no problem with that Pimple version. The answer you got on forum is confused about how version constraints work.

```
    - rarst/wps 1.2 requires pimple/pimple ^3.2.3 -> satisfiable by pimple/pimple[v3.4.0].
```

From quick look at Composer docs, you might be mixing up your arguments `--with-all-dependencies` is an argument for `update`,  `--update-with-all-dependencies` is the one for `require`. Strangely output suggest former, might be a bug.

You need to work out a correct Composer command that both requires a new package and allows installed packages to update.
