### ISSUE TITLE
Possibility to hook into plugin

### ISSUE THREAD

**Issue by matczar** [Rarst/wps#3]
At first, thanks for the great plugin - it make a great work!

However, I have one request: could you add some WordPress hook in main plugin's class, to easy hook into it? I would like to set editor to PrettyPageHandler.

Or maybe there is another way to set editor to handler?

**Comment by Rarst** [comment]
You can access plugin instance via `$wps` global, which also serves as container for all the things.

From quick search through my snippets you can set editor like this for example:

```php
add_action( 'plugins_loaded', function () {

	global $wps;

	if ( ! empty( $wps ) ) {
		/** @var \Whoops\Handler\PrettyPageHandler $handler */
		$handler = $wps['handler.pretty'];
		$handler->setEditor( 'phpstorm-remote-call' );
	}
} );
```

Does this answer your question?

**Comment by matczar** [comment]
Definitely yes. Thank you.
