### ISSUE TITLE
Require it as theme dependency

### ISSUE THREAD

**Issue by kaisermann** [Rarst/wps#4]
Is there anyway we could require `wps` as a theme dependency rather than a `wordpress-plugin`? 

Thanks 😉

**Comment by Rarst** [comment]
In a site level Composer stack it should sort of just work, if your theme requires it then site will put the plugin where plugins go.

If you want to include in in standalone theme-level build... I suppose it should work if you customize path within theme and take care of instantiation in it: https://github.com/Rarst/wps/blob/master/wps.php#L38-L39

If it's anything public it would probably be a good idea to handle _both_ cases.

Does this answer your question?

**Comment by kaisermann** [comment]
Yeah it answers a little bit! Although, my main point was that the `"type": "wordpress-plugin"` makes the required files go to a `wp-content/plugins/` directory inside my theme files.

If I manually copy the `wps` files to my theme's `lib` directory and configure the `autoload.files` with the `wps.php`, it works as expected. The only downsize is that I had to put the files manually. 

(I'm sorry if there's a simple way of overriding this, but I'm not that used to composer just yet)

**Comment by Rarst** [comment]
Since that path is handled by composer/installers you can accordingly use its configuration to make location one that makes sense within your theme, see https://github.com/composer/installers#custom-install-paths

Autoload should be handled "magically", just require the one generated by Composer for you.

**Comment by kaisermann** [comment]
Oh, I didn't know about that! Thank you very much, it's working fine now! 💯
