### ISSUE TITLE
Support PHP cli

### ISSUE THREAD

**Issue by nlemoine** [Rarst/wps#7]
Hi, 

Errors occurring while running a WP-CLI command do not show up. Could you add a CLI handler? 

@onnimonni has already [done this](https://github.com/onnimonni/wps/commit/794fe06675d4aba56b6261884a8bad2acae76f1f) but it would be great if something similar would be added to this repo.

**Comment by Rarst** [comment]
I'll take a look. :) That seems like a lot of code though, so maybe something more basic for baseline implementation.

**Comment by onnimonni** [comment]
I did not create a PR back then because I was just tinkering with the code and that's quite terrible implementation. Hopefully that can be used to some extent for this feature.

**Comment by nlemoine** [comment]
Thanks considering this enhancement @Rarst! Maybe the [`PlainTextHandler`](https://github.com/filp/whoops/blob/master/docs/API%20Documentation.md#-whoopsutilmisciscommandline) should be enough for a first shot as it would solve failing silently when running PHP from cli.

**Comment by nlemoine** [comment]
👍 Looks good to me. Errors happening on cli are now handled by Whoops.

But output is pretty raw. I stumbled upon [Collision](https://github.com/nunomaduro/collision) which does a really great job at formatting CLI errors. I gave it a shot replacing `PlainTextHandler` by theirs: `new \NunoMaduro\Collision\Handler()`.

But It adds some dependencies and a more restrictive PHP support. Up to you!

**Comment by nlemoine** [comment]
Whoops, I checked too fast. Whether you use `\Whoops\Handler\PlainTextHandler` or `\NunoMaduro\Collision\Handler()`, you need to conditionally add the handler: 
```php
if (Whoops\Util\Misc::isCommandLine()) {
    $run->pushHandler( $plugin['handler.text'] );
}
```

**Comment by Rarst** [comment]
Thanks, I saw that pretty handler opt out of CLI but hadn't checked the other way around. Fixed.

I don't think I want to add third party handler right now. It should be easy to add it to wps via container if anyone wants it.

Might revisit it later, but plain text should be good enough for minor release.

**Comment by nlemoine** [comment]
No problem! Thanks for considering the request so fast.
