### ISSUE TITLE
Include plugin version in plugin header

### ISSUE THREAD

**Issue by slaFFik** [Rarst/wps#9]
Currently, it's empty, so when checking in WP admin area - I don't know which version I'm using and whether I should update it.
Would be very helpful to have `Version: 1.2` in `wps.php`.

**Comment by Rarst** [comment]
Ugh, I am on the fence about it. My plugins are meant to be Composer first and I routinely forget to update header versions for releases.

Really unless I have a hook in place that prevents me from releasing with incorrect header I give up on this. I will revisit what's the current hooks situation for PHP projects (saw some lib recently), but no promises unless it comes together easy.

**Comment by Rarst** [comment]
Yeah, after a refresher on the topic I now remember there isn't actually a hook for tags in git so this snowballs to fool proof.

I will make effort to be more thorough about versions, but as above it's Composer first. I think it's worse to ship a _wrong_ version in header than none, which totally happened before.
